name: process_invitation
description: Process invitation acceptances and declines for the Thingzee household system
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_appwrite: ^14.0.0
  http: ^1.3.0
