name: process_invitation
description: Process invitation acceptances and declines for the Thingzee household system
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_appwrite: ^14.0.0
