builders:
  object_box_builder:
    import: "package:repository_ob/object_box_builder.dart"
    builder_factories: ["objectBoxBuilder"]
    build_extensions: { ".dart": [".ob.dart"] }
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      repository_ob|object_box_builder:
        enabled: true
        generate_for:
          - lib/model/expiration_date.dart
          - lib/model/household_member.dart
          - lib/model/inventory.dart
          - lib/model/item.dart
          - lib/model/location.dart
          - lib/model/manufacturer.dart
          - lib/model/product.dart
