version: '3'

vars:
  API_KEY: '{{.APPWRITE_KEY}}'

tasks:
  default:
    cmds:
      - task: process-invitation
      - task: manage-invitations

  process-invitation:
    dir: process_invitation
    cmds:
      - echo "Deploying process_invitation function"
      - python3 -c "import os; os.makedirs('build', exist_ok=True)"
      - python3 -c "import tarfile, os; tar = tarfile.open('build/code.tar.gz', 'w:gz'); tar.add('lib'); tar.add('pubspec.yaml'); tar.add('pubspec.lock'); tar.close()"
      - dart pub get
      - appwrite functions create --function-id=process_invitation --name="Process Invitation" --runtime="dart-2.17" --execute=["users"] --events=["databases.*.collections.invitation.documents.update"] || echo "Function exists"
      - appwrite functions create-variable --function-id=process_invitation --key=APPWRITE_API_KEY --value="{{.API_KEY}}" || echo "Variable exists"
      - appwrite functions create-deployment --function-id=process_invitation --code=build/code.tar.gz --entrypoint="lib/main.dart" --activate=true
      - echo "[SUCCESS] Process_invitation deployment complete"

  manage-invitations:
    dir: manage_invitations
    cmds:
      - echo "Deploying manage_invitations function"
      - dart pub get
      - python3 -c "import os; os.makedirs('build', exist_ok=True)"
      - python3 -c "import tarfile, os; tar = tarfile.open('build/code.tar.gz', 'w:gz'); tar.add('lib'); tar.add('pubspec.yaml'); tar.add('pubspec.lock'); tar.close()"
      - appwrite functions create --function-id=manage_invitations --name="Manage Invitations" --runtime="dart-2.17" --execute=["users"] --schedule="*/30 * * * *" || echo "Function exists"
      - appwrite functions create-variable --function-id=manage_invitations --key=APPWRITE_API_KEY --value="{{.API_KEY}}" || echo "Variable exists"
      - appwrite functions create-deployment --function-id=manage_invitations --code=build/code.tar.gz --entrypoint="lib/main.dart" --activate=true
      - echo "[SUCCESS] Manage_invitations deployment complete"
