name: repository_ha
description: Home Assistant backend repository code.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  log:
    path: ../log
  repository:
    path: ../repository
  util:
    path: ../util
  uuid: ^4.2.1
  web_socket_channel: ^2.4.5

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
