name: thingzee
description: Store, track, rate and share your favorite things.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  appwrite: ^12.0.1
  archive: ^3.3.7
  camera: ^0.10.5+5
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  el_tooltip: ^2.0.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_inappwebview: ^6.0.0
  fuzzy: ^0.5.1
  google_mlkit_text_recognition: ^0.11.0
  hooks_riverpod: ^2.3.6
  image: ^4.1.3
  intl: ^0.18.1
  log:
    path: packages/log
  logger: ^2.0.2+1
  material_floating_search_bar_2: ^0.5.0
  mealie_api:
    path: packages/mealie_api
  ml_linalg: ^13.11.31
  money2: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  petitparser: ^6.0.2
  qr_mobile_vision: ^5.0.1
  repository:
    path: packages/repository
  repository_appw:
    path: packages/repository_appw
  repository_ob:
    path: packages/repository_ob
  riverpod_annotation: ^2.1.1
  settings_ui: ^2.0.2
  share_plus: ^7.0.2
  stack_trace: ^1.11.0
  stats:
    path: packages/stats
  url_launcher: ^6.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image_available.png
    - assets/images/no_image_small.png
    - assets/images/account.png

  fonts:
    - family: IconLibrary
      fonts:
        - asset: fonts/IconLibrary.ttf
