name: thingzee
description: Store, track, rate and share your favorite things.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  appwrite: ^11.0.1
  archive: ^3.3.7
  camera: ^0.10.5+5
  collection: ^1.18.0
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  el_tooltip: ^2.0.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_inappwebview: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_rounded_progress_bar: ^0.3.2
  fuzzy: ^0.5.1
  google_mlkit_text_recognition: ^0.11.0
  hooks_riverpod: ^2.3.6
  image: ^4.1.3
  intl: ^0.18.1
  log:
    path: packages/log
  logger: ^2.0.2+1
  material_floating_search_bar_2: ^0.5.0
  mealie_api:
    path: packages/mealie_api
  meta: ^1.11.0
  ml_linalg: ^13.12.2
  money2: ^4.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  qr_mobile_vision: ^5.0.1
  receipt_ocr:
    path: packages/receipt_ocr
  receipt_parser:
    path: packages/receipt_parser
  repository:
    path: packages/repository
  repository_appw:
    path: packages/repository_appw
  repository_ob:
    path: packages/repository_ob
  riverpod_annotation: ^2.1.1
  settings_ui: ^2.0.2
  share_plus: ^9.0.0
  stack_trace: ^1.11.0
  url_launcher: ^6.2.2
  util:
    path: packages/util
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image_available.png
    - assets/images/no_image_small.png
    - assets/images/account.png

  fonts:
    - family: IconLibrary
      fonts:
        - asset: fonts/IconLibrary.ttf

# Regenerate by running `dart run flutter_native_splash:create`
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#212121"

  android_12:
    color: "#FFFFFF"
    color_dark: "#212121"
