name: sync_household_permissions
description: A function to sync document permissions for all household members
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_appwrite: ^11.0.0
