name: receipt_parser
description: A library for parsing receipt data.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.0.1
  petitparser: ^6.0.2
  repository:
    path: ../repository
  util:
    path: ../util

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.1
  test: ^1.17.0
