name: receipt_parser
description: A library for parsing receipt data.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fuzzy: ^0.5.1
  intl: ^0.18.1
  json_annotation: ^4.0.1
  log:
    path: ../log
  meta: ^1.15.0
  petitparser: ^6.0.2
  util:
    path: ../util
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.1
  test: ^1.17.0
