/// Flutter icons IconLibrary
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconLibrary
///      fonts:
///       - asset: fonts/IconLibrary.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class IconLibrary {
  IconLibrary._();

  static const _kFontFam = 'IconLibrary';
  static const String? _kFontPkg = null;
  static const IconData barcode = IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
