- input:
    - ../packages/repository/lib/model/
  output_dir: ../packages/repository_ob/lib/model/
  db_type: objectbox
  ignore:
    - serializer_datetime.dart
    - filter.dart
    - receipt.dart
# - input:
#     - ../packages/repository/lib/model/
#   output_dir: ../packages/repository_hive/lib/model/
#   db_type: hive
#   ignore:
#     - serializer_datetime.dart
#     - identifier.dart
#     - filter.dart
