// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/household_member.ob.dart';
import 'model/inventory.ob.dart';
import 'model/item.ob.dart';
import 'model/manufacturer.ob.dart';
import 'model/product.ob.dart';
import 'model_custom/history_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 9117861105543333030),
      name: 'ObjectBoxManufacturer',
      lastPropertyId: const IdUid(7, 4027347905943055975),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8962671851432199895),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 534853850960335020),
            name: 'website',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 491023906510423633),
            name: 'muid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7857370170966890870),
            name: 'parentName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6833677880252569975),
            name: 'parentMuid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4027347905943055975),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 7428099248268805432),
      name: 'ObjectBoxProduct',
      lastPropertyId: const IdUid(9, 4714831988172942167),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 9143953678226152578),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 341902253459249865),
            name: 'puid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2392538050400575422),
            name: 'manufacturer',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6372715835582080505),
            name: 'muid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8569655026787145499),
            name: 'upcs',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6452788457756566678),
            name: 'category',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4714831988172942167),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(12, 8845027561250741274),
      name: 'ObjectBoxHistory',
      lastPropertyId: const IdUid(4, 1410544969885562863),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5930073436429162412),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const IdUid(4, 1380383612824248493)),
        ModelProperty(
            id: const IdUid(3, 8507136725000371231),
            name: 'dbHistory',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 1410544969885562863),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(14, 2743826058802040572),
      name: 'ObjectBoxInventory',
      lastPropertyId: const IdUid(12, 7448301853841625850),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 9056680913246608197),
            name: 'amount',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 8684653693421107758),
            name: 'unitCount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5192325408638624988),
            name: 'lastUpdate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5760270407873770334),
            name: 'locations',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5897877644328943369),
            name: 'restock',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8210873934856385730),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const IdUid(5, 3019641394831653558)),
        ModelProperty(
            id: const IdUid(7, 6745209600142358059),
            name: 'iuid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6880088959244528271),
            name: 'units',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 4408203996444102651),
            name: 'dbLastUpdate',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 7946806435019515615),
            name: 'dbExpirationDates',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 7448301853841625850),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(16, 1611655272336628852),
      name: 'ObjectBoxNullableDateTimeSerializer',
      lastPropertyId: const IdUid(2, 1962250420156656810),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(2, 1962250420156656810),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(17, 2183662866210831935),
      name: 'ObjectBoxItem',
      lastPropertyId: const IdUid(14, 6972730156399653636),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7056447120328768215),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const IdUid(7, 2265487539467967031)),
        ModelProperty(
            id: const IdUid(2, 6388154415577016172),
            name: 'id',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4209418296281574048),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6178227767178788053),
            name: 'variety',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1063075903001110635),
            name: 'category',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7818500068996145284),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8957439855027803910),
            name: 'unitCount',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 9076724273805061677),
            name: 'unitName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 6899021128483393415),
            name: 'unitPlural',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1115647715285200717),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 893804246152415796),
            name: 'consumable',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 2920156935710059380),
            name: 'languageCode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 6175421043226721665),
            name: 'lastUpdate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 6972730156399653636),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(18, 6355597710876493410),
      name: 'ObjectBoxItemTranslation',
      lastPropertyId: const IdUid(7, 2218455768959677665),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6728416846686828406),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const IdUid(8, 866918556565432518)),
        ModelProperty(
            id: const IdUid(2, 283520272498643630),
            name: 'languageCode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 957661081092618053),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2477605786470080913),
            name: 'variety',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 563120090522239608),
            name: 'unitName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2677045677771164418),
            name: 'unitPlural',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 2218455768959677665),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(19, 8501125382873435329),
      name: 'ObjectBoxHouseholdMember',
      lastPropertyId: const IdUid(8, 3618722309383559273),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4243342055390721375),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8750205013675183738),
            name: 'isAdmin',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6176841570395132493),
            name: 'timestamp',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8682336750676568002),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4359941432476552937),
            name: 'householdId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4577600509295133427),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 3618722309383559273),
            name: 'userId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(19, 8501125382873435329),
      lastIndexId: const IdUid(8, 866918556565432518),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [
        8566586954295585920,
        8424580053237053064,
        4409076866089830057,
        6867336823909880876,
        2032575102652478660,
        5035609981372595064,
        3723209419512490517,
        36458029675643691,
        9026109327750919290,
        4961829832959724808,
        2251611335733283142
      ],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        57279646016854868,
        2023568673810575159,
        5921365200784546926,
        7056314024111135425,
        3839357041238075661,
        2230598806361440995,
        3461574675591501780,
        4328936514420287378,
        4796539028836325964,
        6997836372642423144,
        5952406950301158294,
        3355537275434974339,
        1052702354648483711,
        4124202752757832297,
        4918676773470177501,
        3063150938887394804,
        8096728495852615076,
        6386881952248259748,
        2097527918487075803,
        5026288376565790065,
        6040227891217577961,
        2915645506796281321,
        2461830532801570432,
        1856176597008648871,
        3916459574677260029,
        3856679234313991003,
        5719439178890724680,
        8607650824692377265,
        6104661389077328605,
        829680582109422048,
        4025734358697509889,
        1728930760721481711,
        6915659985871251568,
        5080861922992731976,
        1667797658952104342,
        4642552144884560139,
        7786677029272803752,
        8357713899618901105,
        7559738479188885525,
        7421044316369511788,
        8899963707085719829,
        4539762830081980506,
        1842500871581494976,
        7635499233144786521,
        6152067401598642879,
        8684262891863985734,
        2800481630876756137,
        3751483311440047393,
        3032133473879599968,
        5421981205332139083,
        5761433883833081952,
        5902732368597070142,
        5642870310487826339,
        8862873893397617478,
        7387687423856593037,
        2028156149330326041,
        1103960621444936317,
        5207382650981158992,
        3049551101808332660,
        8898497516433519050,
        6575382785729127895,
        3045175981976767442,
        4738601771660428828,
        9191167413262940472
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ObjectBoxManufacturer: EntityDefinition<ObjectBoxManufacturer>(
        model: _entities[0],
        toOneRelations: (ObjectBoxManufacturer object) => [],
        toManyRelations: (ObjectBoxManufacturer object) => {},
        getId: (ObjectBoxManufacturer object) => object.objectBoxId,
        setId: (ObjectBoxManufacturer object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxManufacturer object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final websiteOffset = fbb.writeString(object.website);
          final muidOffset = fbb.writeString(object.muid);
          final parentNameOffset = fbb.writeString(object.parentName);
          final parentMuidOffset = fbb.writeString(object.parentMuid);
          fbb.startTable(8);
          fbb.addOffset(0, nameOffset);
          fbb.addOffset(1, websiteOffset);
          fbb.addOffset(2, muidOffset);
          fbb.addOffset(3, parentNameOffset);
          fbb.addOffset(4, parentMuidOffset);
          fbb.addInt64(6, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxManufacturer()
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..website = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..muid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..parentName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..parentMuid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);

          return object;
        }),
    ObjectBoxProduct: EntityDefinition<ObjectBoxProduct>(
        model: _entities[1],
        toOneRelations: (ObjectBoxProduct object) => [],
        toManyRelations: (ObjectBoxProduct object) => {},
        getId: (ObjectBoxProduct object) => object.objectBoxId,
        setId: (ObjectBoxProduct object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxProduct object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final puidOffset = fbb.writeString(object.puid);
          final manufacturerOffset = fbb.writeString(object.manufacturer);
          final muidOffset = fbb.writeString(object.muid);
          final upcsOffset = fbb.writeList(
              object.upcs.map(fbb.writeString).toList(growable: false));
          final categoryOffset = fbb.writeString(object.category);
          fbb.startTable(10);
          fbb.addOffset(0, nameOffset);
          fbb.addOffset(1, puidOffset);
          fbb.addOffset(2, manufacturerOffset);
          fbb.addOffset(3, muidOffset);
          fbb.addOffset(6, upcsOffset);
          fbb.addOffset(7, categoryOffset);
          fbb.addInt64(8, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxProduct()
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..puid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..manufacturer = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..muid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..upcs = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 16, [])
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);

          return object;
        }),
    ObjectBoxHistory: EntityDefinition<ObjectBoxHistory>(
        model: _entities[2],
        toOneRelations: (ObjectBoxHistory object) => [],
        toManyRelations: (ObjectBoxHistory object) => {},
        getId: (ObjectBoxHistory object) => object.objectBoxId,
        setId: (ObjectBoxHistory object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxHistory object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final dbHistoryOffset = fbb.writeString(object.dbHistory);
          fbb.startTable(5);
          fbb.addOffset(0, upcOffset);
          fbb.addOffset(2, dbHistoryOffset);
          fbb.addInt64(3, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxHistory()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..dbHistory = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);

          return object;
        }),
    ObjectBoxInventory: EntityDefinition<ObjectBoxInventory>(
        model: _entities[3],
        toOneRelations: (ObjectBoxInventory object) => [],
        toManyRelations: (ObjectBoxInventory object) => {},
        getId: (ObjectBoxInventory object) => object.objectBoxId,
        setId: (ObjectBoxInventory object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxInventory object, fb.Builder fbb) {
          final locationsOffset = fbb.writeList(
              object.locations.map(fbb.writeString).toList(growable: false));
          final upcOffset = fbb.writeString(object.upc);
          final iuidOffset = fbb.writeString(object.iuid);
          final dbExpirationDatesOffset = fbb.writeList(object.dbExpirationDates
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(13);
          fbb.addFloat64(0, object.amount);
          fbb.addInt64(1, object.unitCount);
          fbb.addInt64(2, object.lastUpdate?.millisecondsSinceEpoch);
          fbb.addOffset(3, locationsOffset);
          fbb.addBool(4, object.restock);
          fbb.addOffset(5, upcOffset);
          fbb.addOffset(6, iuidOffset);
          fbb.addFloat64(7, object.units);
          fbb.addInt64(9, object.dbLastUpdate);
          fbb.addOffset(10, dbExpirationDatesOffset);
          fbb.addInt64(11, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastUpdateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = ObjectBoxInventory()
            ..amount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..unitCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..lastUpdate = lastUpdateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastUpdateValue)
            ..locations = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 10, [])
            ..restock =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false)
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..iuid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..units =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0)
            ..dbLastUpdate =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0)
            ..dbExpirationDates = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 24, [])
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);

          return object;
        }),
    ObjectBoxNullableDateTimeSerializer:
        EntityDefinition<ObjectBoxNullableDateTimeSerializer>(
            model: _entities[4],
            toOneRelations: (ObjectBoxNullableDateTimeSerializer object) => [],
            toManyRelations: (ObjectBoxNullableDateTimeSerializer object) => {},
            getId: (ObjectBoxNullableDateTimeSerializer object) =>
                object.objectBoxId,
            setId: (ObjectBoxNullableDateTimeSerializer object, int id) {
              object.objectBoxId = id;
            },
            objectToFB:
                (ObjectBoxNullableDateTimeSerializer object, fb.Builder fbb) {
              fbb.startTable(3);
              fbb.addInt64(1, object.objectBoxId);
              fbb.finish(fbb.endTable());
              return object.objectBoxId;
            },
            objectFromFB: (Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);

              final object = ObjectBoxNullableDateTimeSerializer()
                ..objectBoxId =
                    const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);

              return object;
            }),
    ObjectBoxItem: EntityDefinition<ObjectBoxItem>(
        model: _entities[5],
        toOneRelations: (ObjectBoxItem object) => [],
        toManyRelations: (ObjectBoxItem object) => {},
        getId: (ObjectBoxItem object) => object.objectBoxId,
        setId: (ObjectBoxItem object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxItem object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final idOffset = fbb.writeString(object.id);
          final nameOffset = fbb.writeString(object.name);
          final varietyOffset = fbb.writeString(object.variety);
          final categoryOffset = fbb.writeString(object.category);
          final typeOffset = fbb.writeString(object.type);
          final unitNameOffset = fbb.writeString(object.unitName);
          final unitPluralOffset = fbb.writeString(object.unitPlural);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          final languageCodeOffset = fbb.writeString(object.languageCode);
          fbb.startTable(15);
          fbb.addOffset(0, upcOffset);
          fbb.addOffset(1, idOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, varietyOffset);
          fbb.addOffset(4, categoryOffset);
          fbb.addOffset(5, typeOffset);
          fbb.addInt64(6, object.unitCount);
          fbb.addOffset(7, unitNameOffset);
          fbb.addOffset(8, unitPluralOffset);
          fbb.addOffset(9, imageUrlOffset);
          fbb.addBool(10, object.consumable);
          fbb.addOffset(11, languageCodeOffset);
          fbb.addInt64(12, object.lastUpdate?.millisecondsSinceEpoch);
          fbb.addInt64(13, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastUpdateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final object = ObjectBoxItem()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..id = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..variety = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..type = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..unitCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..unitName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..unitPlural = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..imageUrl = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '')
            ..consumable =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false)
            ..languageCode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 26, '')
            ..lastUpdate = lastUpdateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastUpdateValue)
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);

          return object;
        }),
    ObjectBoxItemTranslation: EntityDefinition<ObjectBoxItemTranslation>(
        model: _entities[6],
        toOneRelations: (ObjectBoxItemTranslation object) => [],
        toManyRelations: (ObjectBoxItemTranslation object) => {},
        getId: (ObjectBoxItemTranslation object) => object.objectBoxId,
        setId: (ObjectBoxItemTranslation object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxItemTranslation object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final languageCodeOffset = fbb.writeString(object.languageCode);
          final nameOffset = fbb.writeString(object.name);
          final varietyOffset = fbb.writeString(object.variety);
          final unitNameOffset = fbb.writeString(object.unitName);
          final unitPluralOffset = fbb.writeString(object.unitPlural);
          fbb.startTable(8);
          fbb.addOffset(0, upcOffset);
          fbb.addOffset(1, languageCodeOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, varietyOffset);
          fbb.addOffset(4, unitNameOffset);
          fbb.addOffset(5, unitPluralOffset);
          fbb.addInt64(6, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxItemTranslation()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..languageCode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..variety = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..unitName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..unitPlural = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);

          return object;
        }),
    ObjectBoxHouseholdMember: EntityDefinition<ObjectBoxHouseholdMember>(
        model: _entities[7],
        toOneRelations: (ObjectBoxHouseholdMember object) => [],
        toManyRelations: (ObjectBoxHouseholdMember object) => {},
        getId: (ObjectBoxHouseholdMember object) => object.objectBoxId,
        setId: (ObjectBoxHouseholdMember object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxHouseholdMember object, fb.Builder fbb) {
          final emailOffset = fbb.writeString(object.email);
          final householdIdOffset = fbb.writeString(object.householdId);
          final nameOffset = fbb.writeString(object.name);
          final userIdOffset = fbb.writeString(object.userId);
          fbb.startTable(9);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addBool(1, object.isAdmin);
          fbb.addInt64(2, object.timestamp.millisecondsSinceEpoch);
          fbb.addOffset(4, emailOffset);
          fbb.addOffset(5, householdIdOffset);
          fbb.addOffset(6, nameOffset);
          fbb.addOffset(7, userIdOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxHouseholdMember()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..isAdmin =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false)
            ..timestamp = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..householdId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..userId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '');

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ObjectBoxManufacturer] entity fields to define ObjectBox queries.
class ObjectBoxManufacturer_ {
  /// see [ObjectBoxManufacturer.name]
  static final name =
      QueryStringProperty<ObjectBoxManufacturer>(_entities[0].properties[0]);

  /// see [ObjectBoxManufacturer.website]
  static final website =
      QueryStringProperty<ObjectBoxManufacturer>(_entities[0].properties[1]);

  /// see [ObjectBoxManufacturer.muid]
  static final muid =
      QueryStringProperty<ObjectBoxManufacturer>(_entities[0].properties[2]);

  /// see [ObjectBoxManufacturer.parentName]
  static final parentName =
      QueryStringProperty<ObjectBoxManufacturer>(_entities[0].properties[3]);

  /// see [ObjectBoxManufacturer.parentMuid]
  static final parentMuid =
      QueryStringProperty<ObjectBoxManufacturer>(_entities[0].properties[4]);

  /// see [ObjectBoxManufacturer.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxManufacturer>(_entities[0].properties[5]);
}

/// [ObjectBoxProduct] entity fields to define ObjectBox queries.
class ObjectBoxProduct_ {
  /// see [ObjectBoxProduct.name]
  static final name =
      QueryStringProperty<ObjectBoxProduct>(_entities[1].properties[0]);

  /// see [ObjectBoxProduct.puid]
  static final puid =
      QueryStringProperty<ObjectBoxProduct>(_entities[1].properties[1]);

  /// see [ObjectBoxProduct.manufacturer]
  static final manufacturer =
      QueryStringProperty<ObjectBoxProduct>(_entities[1].properties[2]);

  /// see [ObjectBoxProduct.muid]
  static final muid =
      QueryStringProperty<ObjectBoxProduct>(_entities[1].properties[3]);

  /// see [ObjectBoxProduct.upcs]
  static final upcs =
      QueryStringVectorProperty<ObjectBoxProduct>(_entities[1].properties[4]);

  /// see [ObjectBoxProduct.category]
  static final category =
      QueryStringProperty<ObjectBoxProduct>(_entities[1].properties[5]);

  /// see [ObjectBoxProduct.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxProduct>(_entities[1].properties[6]);
}

/// [ObjectBoxHistory] entity fields to define ObjectBox queries.
class ObjectBoxHistory_ {
  /// see [ObjectBoxHistory.upc]
  static final upc =
      QueryStringProperty<ObjectBoxHistory>(_entities[2].properties[0]);

  /// see [ObjectBoxHistory.dbHistory]
  static final dbHistory =
      QueryStringProperty<ObjectBoxHistory>(_entities[2].properties[1]);

  /// see [ObjectBoxHistory.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxHistory>(_entities[2].properties[2]);
}

/// [ObjectBoxInventory] entity fields to define ObjectBox queries.
class ObjectBoxInventory_ {
  /// see [ObjectBoxInventory.amount]
  static final amount =
      QueryDoubleProperty<ObjectBoxInventory>(_entities[3].properties[0]);

  /// see [ObjectBoxInventory.unitCount]
  static final unitCount =
      QueryIntegerProperty<ObjectBoxInventory>(_entities[3].properties[1]);

  /// see [ObjectBoxInventory.lastUpdate]
  static final lastUpdate =
      QueryIntegerProperty<ObjectBoxInventory>(_entities[3].properties[2]);

  /// see [ObjectBoxInventory.locations]
  static final locations =
      QueryStringVectorProperty<ObjectBoxInventory>(_entities[3].properties[3]);

  /// see [ObjectBoxInventory.restock]
  static final restock =
      QueryBooleanProperty<ObjectBoxInventory>(_entities[3].properties[4]);

  /// see [ObjectBoxInventory.upc]
  static final upc =
      QueryStringProperty<ObjectBoxInventory>(_entities[3].properties[5]);

  /// see [ObjectBoxInventory.iuid]
  static final iuid =
      QueryStringProperty<ObjectBoxInventory>(_entities[3].properties[6]);

  /// see [ObjectBoxInventory.units]
  static final units =
      QueryDoubleProperty<ObjectBoxInventory>(_entities[3].properties[7]);

  /// see [ObjectBoxInventory.dbLastUpdate]
  static final dbLastUpdate =
      QueryIntegerProperty<ObjectBoxInventory>(_entities[3].properties[8]);

  /// see [ObjectBoxInventory.dbExpirationDates]
  static final dbExpirationDates =
      QueryStringVectorProperty<ObjectBoxInventory>(_entities[3].properties[9]);

  /// see [ObjectBoxInventory.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxInventory>(_entities[3].properties[10]);
}

/// [ObjectBoxNullableDateTimeSerializer] entity fields to define ObjectBox queries.
class ObjectBoxNullableDateTimeSerializer_ {
  /// see [ObjectBoxNullableDateTimeSerializer.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxNullableDateTimeSerializer>(
          _entities[4].properties[0]);
}

/// [ObjectBoxItem] entity fields to define ObjectBox queries.
class ObjectBoxItem_ {
  /// see [ObjectBoxItem.upc]
  static final upc =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[0]);

  /// see [ObjectBoxItem.id]
  static final id =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[1]);

  /// see [ObjectBoxItem.name]
  static final name =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[2]);

  /// see [ObjectBoxItem.variety]
  static final variety =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[3]);

  /// see [ObjectBoxItem.category]
  static final category =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[4]);

  /// see [ObjectBoxItem.type]
  static final type =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[5]);

  /// see [ObjectBoxItem.unitCount]
  static final unitCount =
      QueryIntegerProperty<ObjectBoxItem>(_entities[5].properties[6]);

  /// see [ObjectBoxItem.unitName]
  static final unitName =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[7]);

  /// see [ObjectBoxItem.unitPlural]
  static final unitPlural =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[8]);

  /// see [ObjectBoxItem.imageUrl]
  static final imageUrl =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[9]);

  /// see [ObjectBoxItem.consumable]
  static final consumable =
      QueryBooleanProperty<ObjectBoxItem>(_entities[5].properties[10]);

  /// see [ObjectBoxItem.languageCode]
  static final languageCode =
      QueryStringProperty<ObjectBoxItem>(_entities[5].properties[11]);

  /// see [ObjectBoxItem.lastUpdate]
  static final lastUpdate =
      QueryIntegerProperty<ObjectBoxItem>(_entities[5].properties[12]);

  /// see [ObjectBoxItem.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<ObjectBoxItem>(_entities[5].properties[13]);
}

/// [ObjectBoxItemTranslation] entity fields to define ObjectBox queries.
class ObjectBoxItemTranslation_ {
  /// see [ObjectBoxItemTranslation.upc]
  static final upc =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[0]);

  /// see [ObjectBoxItemTranslation.languageCode]
  static final languageCode =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[1]);

  /// see [ObjectBoxItemTranslation.name]
  static final name =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[2]);

  /// see [ObjectBoxItemTranslation.variety]
  static final variety =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[3]);

  /// see [ObjectBoxItemTranslation.unitName]
  static final unitName =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[4]);

  /// see [ObjectBoxItemTranslation.unitPlural]
  static final unitPlural =
      QueryStringProperty<ObjectBoxItemTranslation>(_entities[6].properties[5]);

  /// see [ObjectBoxItemTranslation.objectBoxId]
  static final objectBoxId = QueryIntegerProperty<ObjectBoxItemTranslation>(
      _entities[6].properties[6]);
}

/// [ObjectBoxHouseholdMember] entity fields to define ObjectBox queries.
class ObjectBoxHouseholdMember_ {
  /// see [ObjectBoxHouseholdMember.objectBoxId]
  static final objectBoxId = QueryIntegerProperty<ObjectBoxHouseholdMember>(
      _entities[7].properties[0]);

  /// see [ObjectBoxHouseholdMember.isAdmin]
  static final isAdmin = QueryBooleanProperty<ObjectBoxHouseholdMember>(
      _entities[7].properties[1]);

  /// see [ObjectBoxHouseholdMember.timestamp]
  static final timestamp = QueryIntegerProperty<ObjectBoxHouseholdMember>(
      _entities[7].properties[2]);

  /// see [ObjectBoxHouseholdMember.email]
  static final email =
      QueryStringProperty<ObjectBoxHouseholdMember>(_entities[7].properties[3]);

  /// see [ObjectBoxHouseholdMember.householdId]
  static final householdId =
      QueryStringProperty<ObjectBoxHouseholdMember>(_entities[7].properties[4]);

  /// see [ObjectBoxHouseholdMember.name]
  static final name =
      QueryStringProperty<ObjectBoxHouseholdMember>(_entities[7].properties[5]);

  /// see [ObjectBoxHouseholdMember.userId]
  static final userId =
      QueryStringProperty<ObjectBoxHouseholdMember>(_entities[7].properties[6]);
}
