// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/expiration_date.ob.dart';
import 'model/household_member.ob.dart';
import 'model/identifier.ob.dart';
import 'model/inventory.ob.dart';
import 'model/invitation.ob.dart';
import 'model/item.ob.dart';
import 'model/item_translation.ob.dart';
import 'model/location.ob.dart';
import 'model/manufacturer.ob.dart';
import 'model/product.ob.dart';
import 'model/shopping_item.ob.dart';
import 'model_custom/history_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(12, 8845027561250741274),
      name: 'ObjectBoxHistory',
      lastPropertyId: const obx_int.IdUid(6, 5915072062979250527),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5930073436429162412),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(4, 1380383612824248493)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8507136725000371231),
            name: 'dbHistory',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1410544969885562863),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1101226047436064246),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5915072062979250527),
            name: 'updated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(22, 4012899901862137920),
      name: 'ObjectBoxShoppingItem',
      lastPropertyId: const obx_int.IdUid(10, 8215490897377098631),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8628836329229902645),
            name: 'upc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 820201786847802226),
            name: 'checked',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7388475517061537137),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6969894426096673671),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2383647298954806222),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6975486646059346812),
            name: 'uid',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(13, 2029329091094395808)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2518258497503168622),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7740798758396629729),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5996623426433638421),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8215490897377098631),
            name: 'listName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(23, 5617203716368242690),
      name: 'ObjectBoxExpirationDate',
      lastPropertyId: const obx_int.IdUid(6, 5009941825621756222),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6579026378944887639),
            name: 'upc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 831465275208694872),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5465059172932761958),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5181857221685227228),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5009941825621756222),
            name: 'expirationDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(24, 3630768207355311219),
      name: 'ObjectBoxHouseholdMember',
      lastPropertyId: const obx_int.IdUid(9, 1031915927988039123),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3568069331178267087),
            name: 'isAdmin',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4208617638673170285),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 966255402964899452),
            name: 'householdId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9133962073779190726),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 877315598077878698),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 290023497277431132),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6834475930770929319),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1031915927988039123),
            name: 'updated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(27, 3953219533055125616),
      name: 'ObjectBoxItemTranslation',
      lastPropertyId: const obx_int.IdUid(10, 5452683376189884727),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7267860042502112182),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(11, 4213499292565708475)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6831898407583824697),
            name: 'languageCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3321971117874646334),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1749363856361136304),
            name: 'variety',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8341800374486486828),
            name: 'unitName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6233360154769207932),
            name: 'unitPlural',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 368772676665533836),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5584264251070601548),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8391273918360532314),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5452683376189884727),
            name: 'updated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(28, 8452859501085368152),
      name: 'ObjectBoxLocation',
      lastPropertyId: const obx_int.IdUid(6, 1606338988648457034),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7778399611768914868),
            name: 'upc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3931233900844926608),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6486463482966279403),
            name: 'quantity',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 409416015550685976),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2931319557728573164),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1606338988648457034),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(29, 581262129450401551),
      name: 'ObjectBoxManufacturer',
      lastPropertyId: const obx_int.IdUid(8, 1105022292556940314),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3907810617333759869),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2180541031118710814),
            name: 'website',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2449045938527716013),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1175724246066708815),
            name: 'parentName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2124781155255253470),
            name: 'parentUid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8001868185928218441),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 653685303515939838),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1105022292556940314),
            name: 'updated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(30, 8399465274193556283),
      name: 'ObjectBoxProduct',
      lastPropertyId: const obx_int.IdUid(9, 3399163884004457587),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7426609939866308802),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6462919763886991225),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4297826609406557658),
            name: 'manufacturer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3500616642506890172),
            name: 'manufacturerUid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 492727764829979964),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4898767467596893260),
            name: 'upcs',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4464046311116010674),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7532009773921367152),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3399163884004457587),
            name: 'updated',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(31, 6926162432641687423),
      name: 'ObjectBoxIdentifier',
      lastPropertyId: const obx_int.IdUid(6, 8586240948035121702),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5410678726010478738),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1807663967015945579),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9036243146704884821),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8711475091176549077),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6323250953147892719),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8586240948035121702),
            name: 'objectBoxId',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(33, 2540654278505596072),
      name: 'ObjectBoxInvitation',
      lastPropertyId: const obx_int.IdUid(8, 3890612321366565942),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4886526616351532385),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4005898155070359559),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1689091036285741600),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7382151092441077988),
            name: 'id',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4020267371748305490),
            name: 'householdId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7740532563086312670),
            name: 'inviterEmail',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7931193660923984117),
            name: 'inviterUserId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3890612321366565942),
            name: 'recipientEmail',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(35, 5152461968206283516),
      name: 'ObjectBoxInventory',
      lastPropertyId: const obx_int.IdUid(11, 1190199954154274132),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8964229541773848282),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3440533745405522456),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7035360007770370889),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6270015848130356063),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5674885897791624616),
            name: 'unitCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5882402607567144245),
            name: 'locations',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3053833550218156698),
            name: 'restock',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1789632838260684894),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 406355796078745241),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(14, 5084249045812672256)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2784720897502417262),
            name: 'dbExpirationDates',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1190199954154274132),
            name: 'dbLastUpdate',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(36, 3273902510118498833),
      name: 'ObjectBoxItem',
      lastPropertyId: const obx_int.IdUid(16, 1027817466268410003),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4684593359481692798),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5100801697835865734),
            name: 'created',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2387724033038358019),
            name: 'updated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2993214405043338500),
            name: 'upc',
            type: 9,
            flags: 34848,
            indexId: const obx_int.IdUid(15, 5640924439430478188)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2836486313281949926),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2795026740359050796),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 9162136845378160375),
            name: 'variety',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6681774777843313916),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2304468752005070714),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5213760180506748170),
            name: 'typeId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 27938287720804381),
            name: 'unitCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 2695033673185837137),
            name: 'unitName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3099774151825098265),
            name: 'unitPlural',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 8944616525533146781),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7169118763766002325),
            name: 'consumable',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1027817466268410003),
            name: 'languageCode',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(36, 3273902510118498833),
      lastIndexId: const obx_int.IdUid(15, 5640924439430478188),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        8566586954295585920,
        8424580053237053064,
        4409076866089830057,
        6867336823909880876,
        2032575102652478660,
        5035609981372595064,
        3723209419512490517,
        36458029675643691,
        9026109327750919290,
        4961829832959724808,
        2251611335733283142,
        1611655272336628852,
        9117861105543333030,
        7428099248268805432,
        2743826058802040572,
        2183662866210831935,
        6355597710876493410,
        8501125382873435329,
        6997640042144843407,
        3255552557810191530,
        2424801468099308795,
        4842040687820616720,
        1511122922272980926,
        3164051957900951727
      ],
      retiredIndexUids: const [8142794481267609707],
      retiredPropertyUids: const [
        57279646016854868,
        2023568673810575159,
        5921365200784546926,
        7056314024111135425,
        3839357041238075661,
        2230598806361440995,
        3461574675591501780,
        4328936514420287378,
        4796539028836325964,
        6997836372642423144,
        5952406950301158294,
        3355537275434974339,
        1052702354648483711,
        4124202752757832297,
        4918676773470177501,
        3063150938887394804,
        8096728495852615076,
        6386881952248259748,
        2097527918487075803,
        5026288376565790065,
        6040227891217577961,
        2915645506796281321,
        2461830532801570432,
        1856176597008648871,
        3916459574677260029,
        3856679234313991003,
        5719439178890724680,
        8607650824692377265,
        6104661389077328605,
        829680582109422048,
        4025734358697509889,
        1728930760721481711,
        6915659985871251568,
        5080861922992731976,
        1667797658952104342,
        4642552144884560139,
        7786677029272803752,
        8357713899618901105,
        7559738479188885525,
        7421044316369511788,
        8899963707085719829,
        4539762830081980506,
        1842500871581494976,
        7635499233144786521,
        6152067401598642879,
        8684262891863985734,
        2800481630876756137,
        3751483311440047393,
        3032133473879599968,
        5421981205332139083,
        5761433883833081952,
        5902732368597070142,
        5642870310487826339,
        8862873893397617478,
        7387687423856593037,
        2028156149330326041,
        1103960621444936317,
        5207382650981158992,
        3049551101808332660,
        8898497516433519050,
        6575382785729127895,
        3045175981976767442,
        4738601771660428828,
        9191167413262940472,
        1962250420156656810,
        8456053334622007497,
        4224742095922657995,
        6745209600142358059,
        491023906510423633,
        6833677880252569975,
        341902253459249865,
        6372715835582080505,
        8962671851432199895,
        534853850960335020,
        7857370170966890870,
        4027347905943055975,
        969651414277014105,
        7669460921779526709,
        9143953678226152578,
        2392538050400575422,
        8569655026787145499,
        6452788457756566678,
        4714831988172942167,
        3745727551011118418,
        5003022832811822058,
        9056680913246608197,
        8684653693421107758,
        5192325408638624988,
        5760270407873770334,
        5897877644328943369,
        8210873934856385730,
        6880088959244528271,
        4408203996444102651,
        7946806435019515615,
        7448301853841625850,
        4143090653879973508,
        7056447120328768215,
        6388154415577016172,
        4209418296281574048,
        6178227767178788053,
        1063075903001110635,
        7818500068996145284,
        8957439855027803910,
        9076724273805061677,
        6899021128483393415,
        1115647715285200717,
        893804246152415796,
        2920156935710059380,
        6175421043226721665,
        6972730156399653636,
        5327912492728875812,
        6728416846686828406,
        283520272498643630,
        957661081092618053,
        2477605786470080913,
        563120090522239608,
        2677045677771164418,
        2218455768959677665,
        2320097251911814411,
        4243342055390721375,
        8750205013675183738,
        6176841570395132493,
        8682336750676568002,
        4359941432476552937,
        4577600509295133427,
        3618722309383559273,
        5207115531357652064,
        2174772148580454816,
        189495645213970810,
        920624336766919493,
        8027817434216091028,
        9125561795024444450,
        1058588288007546192,
        7608776388611083432,
        1213347897950107873,
        596113066098669458,
        3965590369990621244,
        7543468242257706711,
        592784928820256951,
        8432369276528276973,
        5133401553044031820,
        1409804839355144907,
        4901825100975296988,
        4555738625603270309,
        6561748397873684137,
        310986992928624842,
        7816061209567866527,
        7920296738618385040,
        4540687088627323783,
        1743567812000270236,
        3283187960644019746,
        3789302729946291262,
        379222046820891227,
        7091728040505849939,
        1636634476981007687,
        9116542872001265340,
        8010882142712419719,
        6884647754859486833,
        1692820663667485931,
        6786393335707745360,
        8343660129430174024,
        6275782331319882540,
        6596094317940506748,
        4816689250536618732,
        1978609951305768243,
        1431437387687628276,
        3241574036404653701,
        990711167040717612,
        886880915940834802,
        4713759987857363154,
        6814295420645616934,
        8110034338945550958,
        4354940091097999311,
        7287175140036427301,
        211053890509625994,
        4494473553475034225,
        6328966243408085845,
        4162491639111332433,
        6196793968835640231,
        2845428131231157014,
        6563123697625444326,
        6725266228359140838,
        2260494015855780164,
        3497041783885935618,
        7470005932937188047,
        7642552518931337978,
        7855442706897693439,
        8808233293747501380,
        3554900412404725287
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ObjectBoxHistory: obx_int.EntityDefinition<ObjectBoxHistory>(
        model: _entities[0],
        toOneRelations: (ObjectBoxHistory object) => [],
        toManyRelations: (ObjectBoxHistory object) => {},
        getId: (ObjectBoxHistory object) => object.objectBoxId,
        setId: (ObjectBoxHistory object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxHistory object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final dbHistoryOffset = fbb.writeString(object.dbHistory);
          fbb.startTable(7);
          fbb.addOffset(0, upcOffset);
          fbb.addOffset(2, dbHistoryOffset);
          fbb.addInt64(3, object.objectBoxId);
          fbb.addInt64(4, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updated?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = ObjectBoxHistory()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..dbHistory = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue);

          return object;
        }),
    ObjectBoxShoppingItem: obx_int.EntityDefinition<ObjectBoxShoppingItem>(
        model: _entities[1],
        toOneRelations: (ObjectBoxShoppingItem object) => [],
        toManyRelations: (ObjectBoxShoppingItem object) => {},
        getId: (ObjectBoxShoppingItem object) => object.objectBoxId,
        setId: (ObjectBoxShoppingItem object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxShoppingItem object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset = fbb.writeString(object.name);
          final categoryOffset = fbb.writeString(object.category);
          final listNameOffset = fbb.writeString(object.listName);
          fbb.startTable(11);
          fbb.addOffset(0, upcOffset);
          fbb.addBool(1, object.checked);
          fbb.addInt64(2, object.objectBoxId);
          fbb.addInt64(3, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updated?.millisecondsSinceEpoch);
          fbb.addOffset(5, uidOffset);
          fbb.addOffset(6, nameOffset);
          fbb.addOffset(7, categoryOffset);
          fbb.addFloat64(8, object.price);
          fbb.addOffset(9, listNameOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = ObjectBoxShoppingItem()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..checked =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false)
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..price =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..listName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '');

          return object;
        }),
    ObjectBoxExpirationDate: obx_int.EntityDefinition<ObjectBoxExpirationDate>(
        model: _entities[2],
        toOneRelations: (ObjectBoxExpirationDate object) => [],
        toManyRelations: (ObjectBoxExpirationDate object) => {},
        getId: (ObjectBoxExpirationDate object) => object.objectBoxId,
        setId: (ObjectBoxExpirationDate object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxExpirationDate object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          fbb.startTable(7);
          fbb.addOffset(0, upcOffset);
          fbb.addInt64(2, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(3, object.objectBoxId);
          fbb.addInt64(4, object.updated?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.expirationDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final expirationDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = ObjectBoxExpirationDate()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..expirationDate = expirationDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(expirationDateValue);

          return object;
        }),
    ObjectBoxHouseholdMember: obx_int.EntityDefinition<
            ObjectBoxHouseholdMember>(
        model: _entities[3],
        toOneRelations: (ObjectBoxHouseholdMember object) => [],
        toManyRelations: (ObjectBoxHouseholdMember object) => {},
        getId: (ObjectBoxHouseholdMember object) => object.objectBoxId,
        setId: (ObjectBoxHouseholdMember object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxHouseholdMember object, fb.Builder fbb) {
          final emailOffset = fbb.writeString(object.email);
          final householdIdOffset = fbb.writeString(object.householdId);
          final nameOffset = fbb.writeString(object.name);
          final userIdOffset = fbb.writeString(object.userId);
          fbb.startTable(10);
          fbb.addBool(0, object.isAdmin);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, householdIdOffset);
          fbb.addOffset(4, nameOffset);
          fbb.addOffset(5, userIdOffset);
          fbb.addInt64(6, object.objectBoxId);
          fbb.addInt64(7, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updated?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final object = ObjectBoxHouseholdMember()
            ..isAdmin =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 4, false)
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..householdId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..userId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue);

          return object;
        }),
    ObjectBoxItemTranslation:
        obx_int.EntityDefinition<ObjectBoxItemTranslation>(
            model: _entities[4],
            toOneRelations: (ObjectBoxItemTranslation object) => [],
            toManyRelations: (ObjectBoxItemTranslation object) => {},
            getId: (ObjectBoxItemTranslation object) => object.objectBoxId,
            setId: (ObjectBoxItemTranslation object, int id) {
              object.objectBoxId = id;
            },
            objectToFB: (ObjectBoxItemTranslation object, fb.Builder fbb) {
              final upcOffset = fbb.writeString(object.upc);
              final languageCodeOffset = fbb.writeString(object.languageCode);
              final nameOffset = fbb.writeString(object.name);
              final varietyOffset = fbb.writeString(object.variety);
              final unitNameOffset = fbb.writeString(object.unitName);
              final unitPluralOffset = fbb.writeString(object.unitPlural);
              final typeOffset = fbb.writeString(object.type);
              fbb.startTable(11);
              fbb.addOffset(0, upcOffset);
              fbb.addOffset(1, languageCodeOffset);
              fbb.addOffset(2, nameOffset);
              fbb.addOffset(3, varietyOffset);
              fbb.addOffset(4, unitNameOffset);
              fbb.addOffset(5, unitPluralOffset);
              fbb.addOffset(6, typeOffset);
              fbb.addInt64(7, object.objectBoxId);
              fbb.addInt64(8, object.created?.millisecondsSinceEpoch);
              fbb.addInt64(9, object.updated?.millisecondsSinceEpoch);
              fbb.finish(fbb.endTable());
              return object.objectBoxId;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final createdValue = const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 20);
              final updatedValue = const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 22);
              final object = ObjectBoxItemTranslation()
                ..upc = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 4, '')
                ..languageCode = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 6, '')
                ..name = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 8, '')
                ..variety = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 10, '')
                ..unitName = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 12, '')
                ..unitPlural = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 14, '')
                ..type = const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 16, '')
                ..objectBoxId =
                    const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0)
                ..created = createdValue == null
                    ? null
                    : DateTime.fromMillisecondsSinceEpoch(createdValue)
                ..updated = updatedValue == null
                    ? null
                    : DateTime.fromMillisecondsSinceEpoch(updatedValue);

              return object;
            }),
    ObjectBoxLocation: obx_int.EntityDefinition<ObjectBoxLocation>(
        model: _entities[5],
        toOneRelations: (ObjectBoxLocation object) => [],
        toManyRelations: (ObjectBoxLocation object) => {},
        getId: (ObjectBoxLocation object) => object.objectBoxId,
        setId: (ObjectBoxLocation object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxLocation object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addOffset(0, upcOffset);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.quantity);
          fbb.addInt64(3, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updated?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = ObjectBoxLocation()
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..quantity = const fb.Float64Reader()
                .vTableGetNullable(buffer, rootOffset, 8)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);

          return object;
        }),
    ObjectBoxManufacturer: obx_int.EntityDefinition<ObjectBoxManufacturer>(
        model: _entities[6],
        toOneRelations: (ObjectBoxManufacturer object) => [],
        toManyRelations: (ObjectBoxManufacturer object) => {},
        getId: (ObjectBoxManufacturer object) => object.objectBoxId,
        setId: (ObjectBoxManufacturer object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxManufacturer object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final websiteOffset = fbb.writeString(object.website);
          final uidOffset = fbb.writeString(object.uid);
          final parentNameOffset = fbb.writeString(object.parentName);
          final parentUidOffset = fbb.writeString(object.parentUid);
          fbb.startTable(9);
          fbb.addOffset(0, nameOffset);
          fbb.addOffset(1, websiteOffset);
          fbb.addOffset(2, uidOffset);
          fbb.addOffset(3, parentNameOffset);
          fbb.addOffset(4, parentUidOffset);
          fbb.addInt64(5, object.objectBoxId);
          fbb.addInt64(6, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.updated?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final object = ObjectBoxManufacturer()
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..website = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..parentName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..parentUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue);

          return object;
        }),
    ObjectBoxProduct: obx_int.EntityDefinition<ObjectBoxProduct>(
        model: _entities[7],
        toOneRelations: (ObjectBoxProduct object) => [],
        toManyRelations: (ObjectBoxProduct object) => {},
        getId: (ObjectBoxProduct object) => object.objectBoxId,
        setId: (ObjectBoxProduct object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxProduct object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final uidOffset = fbb.writeString(object.uid);
          final manufacturerOffset = fbb.writeString(object.manufacturer);
          final manufacturerUidOffset = fbb.writeString(object.manufacturerUid);
          final categoryOffset = fbb.writeString(object.category);
          final upcsOffset = fbb.writeList(
              object.upcs.map(fbb.writeString).toList(growable: false));
          fbb.startTable(10);
          fbb.addOffset(0, nameOffset);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, manufacturerOffset);
          fbb.addOffset(3, manufacturerUidOffset);
          fbb.addOffset(4, categoryOffset);
          fbb.addOffset(5, upcsOffset);
          fbb.addInt64(6, object.objectBoxId);
          fbb.addInt64(7, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updated?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final object = ObjectBoxProduct()
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..manufacturer = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..manufacturerUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..upcs = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 14, [])
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue);

          return object;
        }),
    ObjectBoxIdentifier: obx_int.EntityDefinition<ObjectBoxIdentifier>(
        model: _entities[8],
        toOneRelations: (ObjectBoxIdentifier object) => [],
        toManyRelations: (ObjectBoxIdentifier object) => {},
        getId: (ObjectBoxIdentifier object) => object.objectBoxId,
        setId: (ObjectBoxIdentifier object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxIdentifier object, fb.Builder fbb) {
          final typeOffset = fbb.writeString(object.type);
          final valueOffset = fbb.writeString(object.value);
          final uidOffset = fbb.writeString(object.uid);
          fbb.startTable(7);
          fbb.addOffset(0, typeOffset);
          fbb.addOffset(1, valueOffset);
          fbb.addOffset(2, uidOffset);
          fbb.addInt64(3, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updated?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.objectBoxId);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = ObjectBoxIdentifier()
            ..type = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 4, '')
            ..value = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);

          return object;
        }),
    ObjectBoxInvitation: obx_int.EntityDefinition<ObjectBoxInvitation>(
        model: _entities[9],
        toOneRelations: (ObjectBoxInvitation object) => [],
        toManyRelations: (ObjectBoxInvitation object) => {},
        getId: (ObjectBoxInvitation object) => object.objectBoxId,
        setId: (ObjectBoxInvitation object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxInvitation object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final householdIdOffset = fbb.writeString(object.householdId);
          final inviterEmailOffset = fbb.writeString(object.inviterEmail);
          final inviterUserIdOffset = fbb.writeString(object.inviterUserId);
          final recipientEmailOffset = fbb.writeString(object.recipientEmail);
          fbb.startTable(9);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addInt64(1, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.updated?.millisecondsSinceEpoch);
          fbb.addOffset(3, idOffset);
          fbb.addOffset(4, householdIdOffset);
          fbb.addOffset(5, inviterEmailOffset);
          fbb.addOffset(6, inviterUserIdOffset);
          fbb.addOffset(7, recipientEmailOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = ObjectBoxInvitation()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..id = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..householdId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..inviterEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..inviterUserId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..recipientEmail = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '');

          return object;
        }),
    ObjectBoxInventory: obx_int.EntityDefinition<ObjectBoxInventory>(
        model: _entities[10],
        toOneRelations: (ObjectBoxInventory object) => [],
        toManyRelations: (ObjectBoxInventory object) => {},
        getId: (ObjectBoxInventory object) => object.objectBoxId,
        setId: (ObjectBoxInventory object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxInventory object, fb.Builder fbb) {
          final locationsOffset = fbb.writeList(
              object.locations.map(fbb.writeString).toList(growable: false));
          final uidOffset = fbb.writeString(object.uid);
          final upcOffset = fbb.writeString(object.upc);
          final dbExpirationDatesOffset = fbb.writeList(object.dbExpirationDates
              .map(fbb.writeString)
              .toList(growable: false));
          fbb.startTable(12);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addInt64(1, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.updated?.millisecondsSinceEpoch);
          fbb.addFloat64(3, object.amount);
          fbb.addInt64(4, object.unitCount);
          fbb.addOffset(5, locationsOffset);
          fbb.addBool(6, object.restock);
          fbb.addOffset(7, uidOffset);
          fbb.addOffset(8, upcOffset);
          fbb.addOffset(9, dbExpirationDatesOffset);
          fbb.addInt64(10, object.dbLastUpdate);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = ObjectBoxInventory()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..amount =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..unitCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..locations = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 14, [])
            ..restock =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..dbExpirationDates = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 22, [])
            ..dbLastUpdate =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);

          return object;
        }),
    ObjectBoxItem: obx_int.EntityDefinition<ObjectBoxItem>(
        model: _entities[11],
        toOneRelations: (ObjectBoxItem object) => [],
        toManyRelations: (ObjectBoxItem object) => {},
        getId: (ObjectBoxItem object) => object.objectBoxId,
        setId: (ObjectBoxItem object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (ObjectBoxItem object, fb.Builder fbb) {
          final upcOffset = fbb.writeString(object.upc);
          final uidOffset = fbb.writeString(object.uid);
          final nameOffset = fbb.writeString(object.name);
          final varietyOffset = fbb.writeString(object.variety);
          final categoryOffset = fbb.writeString(object.category);
          final typeOffset = fbb.writeString(object.type);
          final typeIdOffset = fbb.writeString(object.typeId);
          final unitNameOffset = fbb.writeString(object.unitName);
          final unitPluralOffset = fbb.writeString(object.unitPlural);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          final languageCodeOffset = fbb.writeString(object.languageCode);
          fbb.startTable(17);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addInt64(1, object.created?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.updated?.millisecondsSinceEpoch);
          fbb.addOffset(3, upcOffset);
          fbb.addOffset(4, uidOffset);
          fbb.addOffset(5, nameOffset);
          fbb.addOffset(6, varietyOffset);
          fbb.addOffset(7, categoryOffset);
          fbb.addOffset(8, typeOffset);
          fbb.addOffset(9, typeIdOffset);
          fbb.addInt64(10, object.unitCount);
          fbb.addOffset(11, unitNameOffset);
          fbb.addOffset(12, unitPluralOffset);
          fbb.addOffset(13, imageUrlOffset);
          fbb.addBool(14, object.consumable);
          fbb.addOffset(15, languageCodeOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final updatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = ObjectBoxItem()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..created = createdValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdValue)
            ..updated = updatedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedValue)
            ..upc = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..variety = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 16, '')
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..type = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 20, '')
            ..typeId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '')
            ..unitCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
            ..unitName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 26, '')
            ..unitPlural = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '')
            ..imageUrl = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 30, '')
            ..consumable =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false)
            ..languageCode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 34, '');

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObjectBoxHistory] entity fields to define ObjectBox queries.
class ObjectBoxHistory_ {
  /// see [ObjectBoxHistory.upc]
  static final upc =
      obx.QueryStringProperty<ObjectBoxHistory>(_entities[0].properties[0]);

  /// see [ObjectBoxHistory.dbHistory]
  static final dbHistory =
      obx.QueryStringProperty<ObjectBoxHistory>(_entities[0].properties[1]);

  /// see [ObjectBoxHistory.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxHistory>(_entities[0].properties[2]);

  /// see [ObjectBoxHistory.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxHistory>(_entities[0].properties[3]);

  /// see [ObjectBoxHistory.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxHistory>(_entities[0].properties[4]);
}

/// [ObjectBoxShoppingItem] entity fields to define ObjectBox queries.
class ObjectBoxShoppingItem_ {
  /// see [ObjectBoxShoppingItem.upc]
  static final upc = obx.QueryStringProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[0]);

  /// see [ObjectBoxShoppingItem.checked]
  static final checked = obx.QueryBooleanProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[1]);

  /// see [ObjectBoxShoppingItem.objectBoxId]
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[2]);

  /// see [ObjectBoxShoppingItem.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxShoppingItem>(_entities[1].properties[3]);

  /// see [ObjectBoxShoppingItem.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxShoppingItem>(_entities[1].properties[4]);

  /// see [ObjectBoxShoppingItem.uid]
  static final uid = obx.QueryStringProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[5]);

  /// see [ObjectBoxShoppingItem.name]
  static final name = obx.QueryStringProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[6]);

  /// see [ObjectBoxShoppingItem.category]
  static final category = obx.QueryStringProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[7]);

  /// see [ObjectBoxShoppingItem.price]
  static final price = obx.QueryDoubleProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[8]);

  /// see [ObjectBoxShoppingItem.listName]
  static final listName = obx.QueryStringProperty<ObjectBoxShoppingItem>(
      _entities[1].properties[9]);
}

/// [ObjectBoxExpirationDate] entity fields to define ObjectBox queries.
class ObjectBoxExpirationDate_ {
  /// see [ObjectBoxExpirationDate.upc]
  static final upc = obx.QueryStringProperty<ObjectBoxExpirationDate>(
      _entities[2].properties[0]);

  /// see [ObjectBoxExpirationDate.created]
  static final created = obx.QueryDateProperty<ObjectBoxExpirationDate>(
      _entities[2].properties[1]);

  /// see [ObjectBoxExpirationDate.objectBoxId]
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxExpirationDate>(
      _entities[2].properties[2]);

  /// see [ObjectBoxExpirationDate.updated]
  static final updated = obx.QueryDateProperty<ObjectBoxExpirationDate>(
      _entities[2].properties[3]);

  /// see [ObjectBoxExpirationDate.expirationDate]
  static final expirationDate = obx.QueryDateProperty<ObjectBoxExpirationDate>(
      _entities[2].properties[4]);
}

/// [ObjectBoxHouseholdMember] entity fields to define ObjectBox queries.
class ObjectBoxHouseholdMember_ {
  /// see [ObjectBoxHouseholdMember.isAdmin]
  static final isAdmin = obx.QueryBooleanProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[0]);

  /// see [ObjectBoxHouseholdMember.email]
  static final email = obx.QueryStringProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[1]);

  /// see [ObjectBoxHouseholdMember.householdId]
  static final householdId = obx.QueryStringProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[2]);

  /// see [ObjectBoxHouseholdMember.name]
  static final name = obx.QueryStringProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[3]);

  /// see [ObjectBoxHouseholdMember.userId]
  static final userId = obx.QueryStringProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[4]);

  /// see [ObjectBoxHouseholdMember.objectBoxId]
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[5]);

  /// see [ObjectBoxHouseholdMember.created]
  static final created = obx.QueryDateProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[6]);

  /// see [ObjectBoxHouseholdMember.updated]
  static final updated = obx.QueryDateProperty<ObjectBoxHouseholdMember>(
      _entities[3].properties[7]);
}

/// [ObjectBoxItemTranslation] entity fields to define ObjectBox queries.
class ObjectBoxItemTranslation_ {
  /// see [ObjectBoxItemTranslation.upc]
  static final upc = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[0]);

  /// see [ObjectBoxItemTranslation.languageCode]
  static final languageCode = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[1]);

  /// see [ObjectBoxItemTranslation.name]
  static final name = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[2]);

  /// see [ObjectBoxItemTranslation.variety]
  static final variety = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[3]);

  /// see [ObjectBoxItemTranslation.unitName]
  static final unitName = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[4]);

  /// see [ObjectBoxItemTranslation.unitPlural]
  static final unitPlural = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[5]);

  /// see [ObjectBoxItemTranslation.type]
  static final type = obx.QueryStringProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[6]);

  /// see [ObjectBoxItemTranslation.objectBoxId]
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[7]);

  /// see [ObjectBoxItemTranslation.created]
  static final created = obx.QueryDateProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[8]);

  /// see [ObjectBoxItemTranslation.updated]
  static final updated = obx.QueryDateProperty<ObjectBoxItemTranslation>(
      _entities[4].properties[9]);
}

/// [ObjectBoxLocation] entity fields to define ObjectBox queries.
class ObjectBoxLocation_ {
  /// see [ObjectBoxLocation.upc]
  static final upc =
      obx.QueryStringProperty<ObjectBoxLocation>(_entities[5].properties[0]);

  /// see [ObjectBoxLocation.name]
  static final name =
      obx.QueryStringProperty<ObjectBoxLocation>(_entities[5].properties[1]);

  /// see [ObjectBoxLocation.quantity]
  static final quantity =
      obx.QueryDoubleProperty<ObjectBoxLocation>(_entities[5].properties[2]);

  /// see [ObjectBoxLocation.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxLocation>(_entities[5].properties[3]);

  /// see [ObjectBoxLocation.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxLocation>(_entities[5].properties[4]);

  /// see [ObjectBoxLocation.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxLocation>(_entities[5].properties[5]);
}

/// [ObjectBoxManufacturer] entity fields to define ObjectBox queries.
class ObjectBoxManufacturer_ {
  /// see [ObjectBoxManufacturer.name]
  static final name = obx.QueryStringProperty<ObjectBoxManufacturer>(
      _entities[6].properties[0]);

  /// see [ObjectBoxManufacturer.website]
  static final website = obx.QueryStringProperty<ObjectBoxManufacturer>(
      _entities[6].properties[1]);

  /// see [ObjectBoxManufacturer.uid]
  static final uid = obx.QueryStringProperty<ObjectBoxManufacturer>(
      _entities[6].properties[2]);

  /// see [ObjectBoxManufacturer.parentName]
  static final parentName = obx.QueryStringProperty<ObjectBoxManufacturer>(
      _entities[6].properties[3]);

  /// see [ObjectBoxManufacturer.parentUid]
  static final parentUid = obx.QueryStringProperty<ObjectBoxManufacturer>(
      _entities[6].properties[4]);

  /// see [ObjectBoxManufacturer.objectBoxId]
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxManufacturer>(
      _entities[6].properties[5]);

  /// see [ObjectBoxManufacturer.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxManufacturer>(_entities[6].properties[6]);

  /// see [ObjectBoxManufacturer.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxManufacturer>(_entities[6].properties[7]);
}

/// [ObjectBoxProduct] entity fields to define ObjectBox queries.
class ObjectBoxProduct_ {
  /// see [ObjectBoxProduct.name]
  static final name =
      obx.QueryStringProperty<ObjectBoxProduct>(_entities[7].properties[0]);

  /// see [ObjectBoxProduct.uid]
  static final uid =
      obx.QueryStringProperty<ObjectBoxProduct>(_entities[7].properties[1]);

  /// see [ObjectBoxProduct.manufacturer]
  static final manufacturer =
      obx.QueryStringProperty<ObjectBoxProduct>(_entities[7].properties[2]);

  /// see [ObjectBoxProduct.manufacturerUid]
  static final manufacturerUid =
      obx.QueryStringProperty<ObjectBoxProduct>(_entities[7].properties[3]);

  /// see [ObjectBoxProduct.category]
  static final category =
      obx.QueryStringProperty<ObjectBoxProduct>(_entities[7].properties[4]);

  /// see [ObjectBoxProduct.upcs]
  static final upcs = obx.QueryStringVectorProperty<ObjectBoxProduct>(
      _entities[7].properties[5]);

  /// see [ObjectBoxProduct.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxProduct>(_entities[7].properties[6]);

  /// see [ObjectBoxProduct.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxProduct>(_entities[7].properties[7]);

  /// see [ObjectBoxProduct.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxProduct>(_entities[7].properties[8]);
}

/// [ObjectBoxIdentifier] entity fields to define ObjectBox queries.
class ObjectBoxIdentifier_ {
  /// see [ObjectBoxIdentifier.type]
  static final type =
      obx.QueryStringProperty<ObjectBoxIdentifier>(_entities[8].properties[0]);

  /// see [ObjectBoxIdentifier.value]
  static final value =
      obx.QueryStringProperty<ObjectBoxIdentifier>(_entities[8].properties[1]);

  /// see [ObjectBoxIdentifier.uid]
  static final uid =
      obx.QueryStringProperty<ObjectBoxIdentifier>(_entities[8].properties[2]);

  /// see [ObjectBoxIdentifier.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxIdentifier>(_entities[8].properties[3]);

  /// see [ObjectBoxIdentifier.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxIdentifier>(_entities[8].properties[4]);

  /// see [ObjectBoxIdentifier.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxIdentifier>(_entities[8].properties[5]);
}

/// [ObjectBoxInvitation] entity fields to define ObjectBox queries.
class ObjectBoxInvitation_ {
  /// see [ObjectBoxInvitation.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxInvitation>(_entities[9].properties[0]);

  /// see [ObjectBoxInvitation.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxInvitation>(_entities[9].properties[1]);

  /// see [ObjectBoxInvitation.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxInvitation>(_entities[9].properties[2]);

  /// see [ObjectBoxInvitation.id]
  static final id =
      obx.QueryStringProperty<ObjectBoxInvitation>(_entities[9].properties[3]);

  /// see [ObjectBoxInvitation.householdId]
  static final householdId =
      obx.QueryStringProperty<ObjectBoxInvitation>(_entities[9].properties[4]);

  /// see [ObjectBoxInvitation.inviterEmail]
  static final inviterEmail =
      obx.QueryStringProperty<ObjectBoxInvitation>(_entities[9].properties[5]);

  /// see [ObjectBoxInvitation.inviterUserId]
  static final inviterUserId =
      obx.QueryStringProperty<ObjectBoxInvitation>(_entities[9].properties[6]);

  /// see [ObjectBoxInvitation.recipientEmail]
  static final recipientEmail =
      obx.QueryStringProperty<ObjectBoxInvitation>(_entities[9].properties[7]);
}

/// [ObjectBoxInventory] entity fields to define ObjectBox queries.
class ObjectBoxInventory_ {
  /// see [ObjectBoxInventory.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxInventory>(_entities[10].properties[0]);

  /// see [ObjectBoxInventory.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxInventory>(_entities[10].properties[1]);

  /// see [ObjectBoxInventory.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxInventory>(_entities[10].properties[2]);

  /// see [ObjectBoxInventory.amount]
  static final amount =
      obx.QueryDoubleProperty<ObjectBoxInventory>(_entities[10].properties[3]);

  /// see [ObjectBoxInventory.unitCount]
  static final unitCount =
      obx.QueryIntegerProperty<ObjectBoxInventory>(_entities[10].properties[4]);

  /// see [ObjectBoxInventory.locations]
  static final locations = obx.QueryStringVectorProperty<ObjectBoxInventory>(
      _entities[10].properties[5]);

  /// see [ObjectBoxInventory.restock]
  static final restock =
      obx.QueryBooleanProperty<ObjectBoxInventory>(_entities[10].properties[6]);

  /// see [ObjectBoxInventory.uid]
  static final uid =
      obx.QueryStringProperty<ObjectBoxInventory>(_entities[10].properties[7]);

  /// see [ObjectBoxInventory.upc]
  static final upc =
      obx.QueryStringProperty<ObjectBoxInventory>(_entities[10].properties[8]);

  /// see [ObjectBoxInventory.dbExpirationDates]
  static final dbExpirationDates =
      obx.QueryStringVectorProperty<ObjectBoxInventory>(
          _entities[10].properties[9]);

  /// see [ObjectBoxInventory.dbLastUpdate]
  static final dbLastUpdate = obx.QueryIntegerProperty<ObjectBoxInventory>(
      _entities[10].properties[10]);
}

/// [ObjectBoxItem] entity fields to define ObjectBox queries.
class ObjectBoxItem_ {
  /// see [ObjectBoxItem.objectBoxId]
  static final objectBoxId =
      obx.QueryIntegerProperty<ObjectBoxItem>(_entities[11].properties[0]);

  /// see [ObjectBoxItem.created]
  static final created =
      obx.QueryDateProperty<ObjectBoxItem>(_entities[11].properties[1]);

  /// see [ObjectBoxItem.updated]
  static final updated =
      obx.QueryDateProperty<ObjectBoxItem>(_entities[11].properties[2]);

  /// see [ObjectBoxItem.upc]
  static final upc =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[3]);

  /// see [ObjectBoxItem.uid]
  static final uid =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[4]);

  /// see [ObjectBoxItem.name]
  static final name =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[5]);

  /// see [ObjectBoxItem.variety]
  static final variety =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[6]);

  /// see [ObjectBoxItem.category]
  static final category =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[7]);

  /// see [ObjectBoxItem.type]
  static final type =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[8]);

  /// see [ObjectBoxItem.typeId]
  static final typeId =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[9]);

  /// see [ObjectBoxItem.unitCount]
  static final unitCount =
      obx.QueryIntegerProperty<ObjectBoxItem>(_entities[11].properties[10]);

  /// see [ObjectBoxItem.unitName]
  static final unitName =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[11]);

  /// see [ObjectBoxItem.unitPlural]
  static final unitPlural =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[12]);

  /// see [ObjectBoxItem.imageUrl]
  static final imageUrl =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[13]);

  /// see [ObjectBoxItem.consumable]
  static final consumable =
      obx.QueryBooleanProperty<ObjectBoxItem>(_entities[11].properties[14]);

  /// see [ObjectBoxItem.languageCode]
  static final languageCode =
      obx.QueryStringProperty<ObjectBoxItem>(_entities[11].properties[15]);
}
