builders:
  merge_generator:
    import: "package:repository/merge_generator.dart"
    builder_factories: ["mergeGeneratorBuilder"]
    build_extensions: { ".dart": [".merge.dart"] }
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      repository|merge_generator:
        enabled: true
        generate_for:
          include:
            - lib/model/*.dart
          exclude:
            - lib/model/*.g.dart
