builders:
  merge_generator:
    import: "package:repository/merge_generator.dart"
    builder_factories: ["mergeGeneratorBuilder"]
    build_extensions: { ".dart": [".merge.dart"] }
    auto_apply: all_packages
    build_to: source

targets:
  $default:
    builders:
      repository|merge_generator:
        enabled: true
        generate_for:
          - lib/model/inventory.dart
          - lib/model/item.dart
