name: repository
description: Base implementation for models and repositories.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^5.0.0
  build: ^2.4.1
  connectivity_plus: ^4.0.1
  duration: ^3.0.12
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kmeans_cluster:
    path: ../kmeans_cluster
  log:
    path: ../log
  meta: ^1.9.1
  ml_algo: ^16.17.7
  ml_dataframe: ^1.6.0
  ml_linalg: ^13.11.31
  shared_preferences: ^2.2.0
  stats:
    path: ../stats
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  test: ^1.24.3
